# conf/config.yaml

path: "./data/raw/train.csv"
model_output: "./models/predictor.pkl"

split:
  test_size: 0.2
  random_state: 42

model:
  _target_: "random_forest"  # or "logistic_regression"
  logistic_regression:
    max_iter: 1000
  random_forest:
    n_estimators: 100
    random_state: 42
